name: 'NPM Custom Action'

description: 'Installing NPM packages'

inputs:
  path-of-folder:
    description: 'the path of cache'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Cache NPM dependencies
      uses: actions/cache@v3
      with:
        path: ${{ inputs.path-of-folder }}
        key: ${{runner.os}}-node_modules-${{hashFiles('package-lock.json')}}

    - name: Install dependencies
      run: npm install
      shell: bash